language: java
branches:
  only:
  - develop
  - master
  - "/release.*/"
env:
  global:
  - secure: HPq08el/x0bSrq/zXKR8g5XOFVUkK5WFPzhdtEllTc0NMjiLahx4CBS4/j0WSP9Z1ighKZbzqvyMdj0DCwTsUR5dQY5GZIEcYJ79o8orAaC5RMkk5d9zI1vVXe6nNbNfopaEJHee0REfCShT2b1VOQpgZtesMe7Pa4ZEUQHKmy0=
  - secure: oN8TAQnCnNvtwT4gVm92k8ylPSElSOdwkQkeHQG8cIcEjs/rmwuG/dlQRgYGDlCSKwmUEsj9PqCH0VbxftL4xl8z/YPPdkIf0oEPixcTEekT3wVZlWdIgnroqkaHCLbmYyOll6y7zDIgkdaA+AZV3J/Vevpaz4jJdz0MEv+haYM=
  - secure: cYnwHm1Wh63DzEoTA270H5Yc2CGpQ61k2Ya8u1lzA1eRqNFMqUSlcnk+IrlR1M19xo9WQh5Mb3gnHzRfI8fD743IN3hCyGuKpCrjrh5OsHJEkTVMBNEdWm4/WFYw0bp++IQ+i3yoNx8C0wmtXGbA4uhHRB+de34k4osb0VDbC8k=
  - secure: f5C8XlSI30JvPQQEWYl1fSiYv4Jy1TVH3CFzV/48XsVvKS5/cDJO+WKF3myKdjJbPWHEtuy0KdrBjupzqLQzvoPSkN+4CPluwCxtfDhjatqlA35IX4U7a6kHeaA/YGCom6/UH/Panshgjoa9U1NsZxSL1OmfNf7Xdv01TZ7jdpQ=
  - secure: B/waN2y2rIPOFJvHd/kRCudI+oCAnoDuC1U9xA5gO9fH1Hhrlp/iRIn+vm6Lk0UHLapL+HqZ2WQgX5JRkkftgOliBc0jO+Y0DEH/6kOVQFPrk2gvbBlZCEUQDxJY9NlsMjwKyt3iG92R3354fE7oaOu/N+xrxqluwBwBCYCpamY=
  - secure: VT8iWhvTCZZ5/2q/u3+P7YN6Tes30Ij8ljFE9Nl66UuHbNbMRhRsTfVVN27KcA53eiNIFOwLEyM+irS/IfuCkghwmPY9E+Oc6LC8c2czQ517iFkkx1yE3t6TzqRyWaWy2walgeD+ysImqJXCkxUlxsUlffouer+8VSFerVpriyQ=
stages:
- name: Unit Tests
  if: branch = develop
- name: Staging
  if: branch =~ ^release
- name: Master
  if: branch = master
jobs:
  include:
  - stage: Unit Tests
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pdevelop -B -V install
    script: mvn --settings settings.xml -Pdevelop clean test
  - stage: Staging
    install: mvn install --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pstaging -B -V
    script: mvn clean test --settings settings.xml -Dmaven.javadoc.skip=true -Pstaging
      -B -V
    after_success: chmod +x deploy.sh && ./deploy.sh
  - stage: Master
    install: mvn install --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -B -V
    script: mvn --settings settings.xml package
