language: java
branches:
  only:
  - master
  - develop
env:
  global:
  - secure: oCtq1gtWjiNALv1oO2FohOtuva7S54WJFfaUq+2TsBBW8dtxP22RU2DkhmOaAm2UGamXAuLt/hZ68nxO5QoAXqbXxkpzTYibgb85p1HSJTFxttJy+6//Y5jtHCf77mwHvz6WXBWmfmnvnyJuHREu03XVZiCAXHORmdRGNlRx9V8=
  - secure: nhDS+ouVrk7CIBpp6/pFLl2s1kg6lSKorYofVAfq99Eapdexqx9a30vS1CZNumk9GVtgE0AvM0g7+Z+C71All2xKyw0dDLlitfwLX837e7klpKRsrhSGR9+AtxmGAdsGt1po8mSSU5wzB9de+ZLeZswH4tHjM75jJ9dBLjIqmWg=
  - secure: kHxdVI8kbtEyB2O0uqe8Znj/jqAy1mNPy7VADst4vHqYOwa6Apeuk79RSOD8FRi/6DkSVuzvYHXUsKKhm4l+Bd0APnzfyFty0uDD5c/vV02mu92IdQbYhgo/2juP7gX1w32B7QS6eif/76gp9hBN4fs5X1GbSU/RzTdKOOzV7mI=
  - secure: EywXAhdkhIljz5P1EMqI8YA9/PkdEWqCAYd3qj7NhS2y1d5e2pzFMjK1uxmwvJaF9E1ucNmMihcqlEd4JshsmG10j7qHrYCl3w4Pq822zoq6WFeK7efvcsMg6D6diTo7/FdQrAuvHhY4VxhGsi4UfxR5y17tWNYXBXfgMnJC+oU=
  - secure: TFp8jRsokgAfK9SGcq9AkRv6JVXhtBvsVN7csw6Q2OMDHGFDLO48DGI/ze9dECf/KDPTkE/WvQlqI6YMaT6+66W3lutpnOMnPoUiuUhwVKf+MWqzfxD6Ob1DXoSd6mT5LAahfsYGMsHKlgQOdE/2idBKLNlOhjr2+FlRHhRBmhU=
  - secure: Hn63mWzGr+hGfjQ9jx5KxzZOyu6CyZDkshuPaPqgwOHshlWIXSgzCpjENWBafVunaKTEocE7gFjnS5QaJzDaK1zEnmhX6HgkItNaI8xqBmHIGm8+p1TW8EnQ+cx1D6V7A3yi3sDFKEUNu/vjN+lcblS0yvFXOs6HrrlgiPF27GI=
before_install:
- chmod a+x ./deploy.sh
script:
- mvn clean test --settings settings.xml
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./deploy.sh ; fi
