language: java
branches:
  only:
  - master
  - develop
env:
  global:
before_install:
- chmod a+x ./deploy.sh
script:
- mvn clean test --settings settings.xml
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./deploy.sh ; fi
