package org.lappsgrid.vocabulary;


/*
 * DO NOT EDIT THIS FILE.
 *
 * This file is machine generated and any edits will be lost the next
 * time the file is generated. Use the https://github.com/lapps/vocabulary-pages
 * project to make changes.
 */
/**
 * The URI for the most commonly used annotation types.
 *
 * @deeprecated Use the org.lappsgrid.discriminator.Discriminators.Uri class instead.
 * @author Keith Suderman
 */
//@Deprecated
public class Annotations {
   private Annotations() { }

   public static final String Annotation = "http://vocab.lappsgrid.org/Annotation";
   public static final String AudioDocument = "http://vocab.lappsgrid.org/AudioDocument";
   public static final String Constituent = "http://vocab.lappsgrid.org/Constituent";
   public static final String Coreference = "http://vocab.lappsgrid.org/Coreference";
   public static final String Date = "http://vocab.lappsgrid.org/Date";
   public static final String Dependency = "http://vocab.lappsgrid.org/Dependency";
   public static final String DependencyStructure = "http://vocab.lappsgrid.org/DependencyStructure";
   public static final String Document = "http://vocab.lappsgrid.org/Document";
   public static final String GenericRelation = "http://vocab.lappsgrid.org/GenericRelation";
   public static final String Location = "http://vocab.lappsgrid.org/Location";
   public static final String Markable = "http://vocab.lappsgrid.org/Markable";
   public static final String NamedEntity = "http://vocab.lappsgrid.org/NamedEntity";
   public static final String NounChunk = "http://vocab.lappsgrid.org/NounChunk";
   public static final String Organization = "http://vocab.lappsgrid.org/Organization";
   public static final String Paragraph = "http://vocab.lappsgrid.org/Paragraph";
   public static final String Person = "http://vocab.lappsgrid.org/Person";
   public static final String PhraseStructure = "http://vocab.lappsgrid.org/PhraseStructure";
   public static final String Region = "http://vocab.lappsgrid.org/Region";
   public static final String Relation = "http://vocab.lappsgrid.org/Relation";
   public static final String SemanticRole = "http://vocab.lappsgrid.org/SemanticRole";
   public static final String Sentence = "http://vocab.lappsgrid.org/Sentence";
   public static final String TextDocument = "http://vocab.lappsgrid.org/TextDocument";
   public static final String Thing = "http://vocab.lappsgrid.org/Thing";
   public static final String Token = "http://vocab.lappsgrid.org/Token";
   public static final String VerbChunk = "http://vocab.lappsgrid.org/VerbChunk";
}
