/*
 * DO NOT EDIT THIS FILE.
 *
 * This file is machine generated and any edits will be lost the next
 * time the file is generated. Use the https://github.com/lapps/vocabulary-pages
 * project to make changes.
 *
 * Vocabulary v1.3.0-SNAPSHOT
 * Copyright 2019 The Language Applications Grid. 
 */

package org.lappsgrid.vocabulary;

public class Metadata {
	private Metadata() { }

	public static class Thing {
	}

	public static class Annotation extends Thing {
		public static final String PRODUCER = "producer";
		public static final String RULES = "rules";
		public static final String TYPE = "type";
	}

	public static class Region extends Annotation {
	}

	public static class Relation extends Annotation {
	}

	public static class GenericRelation extends Relation {
	}

	public static class SemanticRole extends Relation {
	}

	public static class Paragraph extends Region {
	}

	public static class Sentence extends Region {
	}

	public static class NounChunk extends Region {
	}

	public static class VerbChunk extends Region {
	}

	public static class NamedEntity extends Region {
		public static final String NAMED_ENTITY_CATEGORY_SET = "namedEntityCategorySet";
	}

	public static class Date extends NamedEntity {
	}

	public static class Location extends NamedEntity {
	}

	public static class Organization extends NamedEntity {
	}

	public static class Person extends NamedEntity {
	}

	public static class Token extends Region {
		public static final String POS_TAG_SET = "posTagSet";
	}

	public static class Event extends Region {
		public static final String EVENT_CLASS_SET = "eventClassSet";
	}

	public static class TimeExpression extends Region {
	}

	public static class Coreference extends Annotation {
	}

	public static class Markable extends Region {
	}

	public static class Morphology extends Region {
	}

	public static class Morpheme extends Region {
	}

	public static class SemanticTag extends Region {
		public static final String TAG_SET = "tagSet";
	}

	public static class PhraseStructure extends Annotation {
		public static final String CATEGORY_SET = "categorySet";
	}

	public static class Constituent extends Relation {
	}

	public static class DependencyStructure extends Annotation {
		public static final String DEPENDENCY_SET = "dependencySet";
	}

	public static class Dependency extends Relation {
	}

	public static class Document extends Thing {
	}

	public static class TextDocument extends Document {
	}

	public static class AudioDocument extends Document {
	}

}
